[phases.setup] aptPkgs = ["pkg-config", "libmysqlclient-dev"]

[phases.build] cmds = ["python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[start] cmd = "python manage.py migrate && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT"