# Generated by Django 5.2 on 2025-07-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="matricule",
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
