# Generated by Django 5.2 on 2025-07-14 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_etudiant_matricule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="etudiant",
            name="face_encoding",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="matricule",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="etudiant",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="etudiants/photos/"
            ),
        ),
    ]
