# Generated by Django 5.2 on 2025-07-15 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_cours_nom_alter_presence_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paiement",
            old_name="montant",
            new_name="montant_du",
        ),
        migrations.AddField(
            model_name="paiement",
            name="montant_paye",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="paiement",
            name="paye",
            field=models.BooleanField(default=False),
        ),
    ]
